int64 support
paulscherrerinstitute/s7plc pull request #4
Opened 2021-03-11 14:46 UTC by ZanMaticPratnemer

Support for int64 records and int64 type.

Additionally, rearanged the files into a current EPICS module structure.

2021-04-14 15:44 UTC, ZanMaticPratnemer commented
We found another problem: CPU usage when inSize was 0.
Explained and fixed in: 199d793

2021-04-22 11:42 UTC, dirk-zimoch commented on .gitignore
> +*envPaths
Fix missing newline!

2021-04-22 11:42 UTC, dirk-zimoch commented on GNUmakefile
> +
No, it isn't. It is PSI internal.

2021-04-22 11:43 UTC, dirk-zimoch commented on Makefile.Vx
> +## THIS FILE IS OUTDATED!!
It allows to build the module for EPICS 3.13. Which IS outdated but still in use at PSI.

2021-04-22 11:44 UTC, dirk-zimoch commented on S7plcApp/Db/example_int64.db
> +}
Files without newline at the end will not be accepted.

2021-04-22 11:50 UTC, dirk-zimoch commented
There are a few style guides which I follow and which need to be followed to be accepted for merge.
Please adjust your editor accordingly.
1. No text file ends without a newline.
2. No tabs for indents (except in Makefiles of course). Use 4 spaces.
3. No trailing whitespace at the end of a line.

2021-04-26 13:48 UTC, ZanMaticPratnemer commented
Should I split this into 3 pull requests?
-file structure update,
-int64 support,
-CPU usage fix

2021-04-26 15:06 UTC, dirk-zimoch commented
No need for that. Just give me some days for testing....

2021-05-03 14:03 UTC, dirk-zimoch requested changes
Please test compilation with older EPICS versions as well and avoid compiler warnings. I got warnings about unused variables with 3.14.12 and still a warning about a file with no newline at the end.

2021-05-10 12:29 UTC, dirk-zimoch approved these changes
Looks OK so far. I am now tesing with different EPICS base versions. Let's see how it works with 3.13.
I am not yet quite happy with the test for int64* record availability (>= 3.16.1).  Maybe simply checking if the headers are installed is easier. I will try...

2021-05-12 12:50 UTC, dirk-zimoch commented
I changed the Makfile as follows:
```
# Check for int64 support
ifneq ($(wildcard $(EPICS_BASE)/include/int64*Record.h),)
EPICS_INT64 = true
endif
```
This checks if `in64*Record.h` files are available in base. That is much easier than the check against version number 3.16.1.

2021-05-12 12:56 UTC, dirk-zimoch commented
There is an inconsitency in the products. We get a library `libs7plc.so` and an example executable `S7plcApp`. But there is only one dbd file `s7plc.dbd` and that is for the executable, not for the library. So the name does not even match.
There should be `s7plc.dbd` for `libs7plc.so` (no EPICS base stuff) and `S7plcApp.dbd` for `S7plcApp` (with full base stuff). Maybe capitalisation of "s7" should also be consistent between library and executable.

2021-05-12 13:25 UTC, dirk-zimoch commented
I have now tested to build with 3.14.12, 3.16.0.1, 3.16.1, and 7.0.5.1. So far so good. But it does not build with 3.13.10 any longer. Maybe it is time to drop 3.13 support. In that case the code sould be cleaned up as well: All compiler branches on `EPICS_3_13` sould be removed as well as the 3.13 specific files `compat3_13.h` and `Makefile.Vx`.

2021-05-12 15:57 UTC, dirk-zimoch commented
Woring on Windows compatibility now....

2021-05-12 16:00 UTC, merged

2021-05-20 13:24 UTC, dirk-zimoch commented
Found a problem. I noticed that error are printet twice, because two threads (send and receive thread) are both calling s7plcConnect.
This was not the case before.

2021-05-31 08:56 UTC, dirk-zimoch commented
There are several places in `ai` and `ao` record handling where hwHigh/hwLow are converted to 32 bit int, but they are potentially 64 bit now. Also the possibility that the raw value is 64 bit is not handled.